### ISSUE TITLE
No migrations are pending

### ISSUE THREAD

**Issue by rajansharma3097** [zsevic/nestjs-starter#14]
Željko thanks for creating this NestJS boilerplate.

Actually, we are facing an issue while running migrations. We are getting "`No migrations are pending`" even though the migration file exists in the `database/migration` folder. Could you please help us with this?

Command that we are using to run the migration: `npm run migrate`

Also, we are using `MySQL` instead of postgres.

**Comment by zsevic** [comment]
I'm glad you find this boilerplate useful.

What is the status of the `migrations` table, is the new migration already stored there?

**Comment by rajansharma3097** [comment]
No, the `migrations ` table is empty. There is no entry in it as migrations not processed after running `npm run migrate`.

**Comment by zsevic** [comment]
okay, do the database credentials point to the right database?

**Comment by rajansharma3097** [comment]
Yes, database credentials are correct and pointing to the right database. On running the migrate command, migrations table got created in the database but other migrations didn’t run.

**Comment by zsevic** [comment]
in the initial comment, the `database/migration` directory is mentioned
boilerplate configuration for migrations points to the `database/migrations` directory, so probably that's the issue

**Comment by rajansharma3097** [comment]
@zsevic any other potential issue that we need to look into to make this work?

**Comment by zsevic** [comment]
can you provide more details about the migrations?
I suppose the issue is MySQL-related
